services:
    nginx:
        image: monacco_dev_nginx:latest
        build:
            context: ./nginx
        volumes:
            - ../../:/app
        ports:
            - "${NGINX_PORT}:80"
        links:
            - php
    php:
        image: monacco_dev_php:latest
        build:
            context: ./php
        volumes:
            - ../../:/app
        links:
            - postgres
    postgres:
        image: postgres:latest
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: main
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    adminer:
        image: adminer:latest
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        links:
            - postgres